#!/bin/sh
node language-task.js addkey 'Save' --es 'Guardar' --en 'Save'
node language-task.js addkey 'Server' --es 'Servidor' --en 'Server'
node language-task.js addkey 'QueueName' --es 'nombre de la cola' --en 'Queue name'
node language-task.js addkey 'Exchange' --es 'Canal' --en 'Exchange'
node language-task.js addkey 'Username' --es 'usuario' --en 'Username'
node language-task.js addkey 'Password' --es 'Contraseña' --en 'Password'
node language-task.js addkey 'Virtualhost' --es 'Virtualhost' --en 'Virtualhost'
node language-task.js addkey 'Port' --es 'Puerto' --en 'Port'
node language-task.js addkey 'PrefetchSize' --es 'PrefetchSize' --en 'PrefetchSize'
node language-task.js addkey 'PrefetchCount' --es 'PrefetchCount' --en 'PrefetchCount'
node language-task.js addkey 'Heartbeat' --es 'Heartbeat' --en 'Heartbeat'
node language-task.js addkey 'SchedulesSettings' --es 'Modo de trabajo' --en 'Service work mode'
node language-task.js addkey 'ScheduleSettingsExplains' --es 'Configuracion basica del servicio' --en 'Service basic configuration'
node language-task.js addkey 'workMode' --es 'Mode de trabajo' --en 'Work mode'
node language-task.js addkey 'ActiveOnDemandQueue' --es 'Activar segunda cola para solicitudes a peticion' --en 'Active second queue for on demand request'
node language-task.js addkey 'StopwatchMode' --es 'Mode de Relog' --en 'Stop watch mode'
node language-task.js addkey 'TimeInterval' --es 'Intervalo de tiempo' --en 'TimeInterval'
node language-task.js addkey 'Value' --es 'Valor' --en 'Value'
node language-task.js addkey 'AvailableDate' --es 'Habilitar desde' --en 'Available Date'
node language-task.js addkey 'StartTimeAt' --es 'Iniciar a' --en 'Start Time '
node language-task.js addkey 'EndTimeAt' --es 'Termina a' --en 'End Time'
node language-task.js addkey 'WorkfowWhiteList' --es 'Lista blanca de clase de lotes' --en 'Batch class white list'
node language-task.js addkey 'WorkflowsWitheListExplains' --es 'Habilita las clase de lotes que se pueden trabajar' --en 'Enable batch class to work '
node language-task.js addkey 'Workflow' --es 'Clase de lotes' --en 'Batch class'
node language-task.js addkey 'Available' --es 'Disponibles' --en 'Available'
node language-task.js addkey 'Active' --es 'Activos' --en 'Active'
